# specify some details about the image to use
image: benniwi/learn2code:lecture

vscode:
  extensions:
    - donjayamanne.githistory
    - ms-python.python
    - twxs.cmake
    - mhutchie.git-graph
    - ms-vscode.cpptools-themes
    - cs128.cs128-clang-tidy
    - xaver.clang-format
    - marp-team.marp-vscode
    - zaaack.markdown-editor
    - ms-vscode.cmake-tools
    - ms-azuretools.vscode-docker
    - yzhang.markdown-all-in-one
    - franneck94.c-cpp-runner
    - DavidAnson.vscode-markdownlint
    - mdickin.markdown-shortcuts
    - ElecTreeFrying.insert-random-text

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
